# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fLplpk56r20vmpckuV-H-_mM32veWKYR
"""

import streamlit as st
import numpy as np
import pickle

kmeans = pickle.load(open("kmeans.pkl", "rb"))
dbscan = pickle.load(open("dbscan.pkl", "rb"))
scaler = pickle.load(open("scaler.pkl", "rb"))

st.title("Iris Clustering App")

sl = st.number_input("Sepal Length")
sw = st.number_input("Sepal Width")
pl = st.number_input("Petal Length")
pw = st.number_input("Petal Width")

if st.button("Predict Cluster"):
    data = np.array([[sl, sw, pl, pw]])
    data_scaled = scaler.transform(data)

    st.success(f"K-Means Cluster: {kmeans.predict(data_scaled)[0]}")
    st.success(f"DBSCAN Cluster: {dbscan.fit_predict(data_scaled)[0]}")